### ISSUE TITLE
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

### ISSUE THREAD

**Issue by gfox1984** [JiarongGu/ReactCoreTemplate#1]
Hi,

Thanks for this example, but I'm having an issue when I clone the repo and run it:

![spa error](https://user-images.githubusercontent.com/14998184/47576618-37fb7f80-d945-11e8-943d-17fa6530d643.png)

I don't have such error when I run the default reactredux project that comes with .net core.

I'm on .net core 2.1.5 (2.1.403 SDK).

**Comment by JiarongGu** [comment]
you need to run the npm run build:all inside of ClientApp manually before run the donet core project, because this is not using the ReactScript which the .net core current monitoring on the console, which causing slowness for development
